```{r}
library(tidyverse)
library(modelr)
```

```{r}
#current dataset to model
sim1a <- tibble(
  x = rep(1:10, each = 3),
  y = x * 1.5 + 6 + rt(length(x), df = 2)
)

sim1a


```

```{r}
models <- tibble(
  a1 = runif(250, -20, 40),
  a2 = runif(250, -5, 5)
)

models

ggplot(data = sim1) + 
  geom_abline(data = models, aes(intercept = a1, slope = a2), alpha = 1/4) + 
  geom_point(aes(x, y))
```

```{r}
# this function outputs a series of y-values when given a matrix containing y-intercepts and slopes, and a dataset
model1 <- function(a, data) {
  a[1] + a[2] * data$x
}
```

```{r}
measure_distance <- function(mod, data) {
  diff <- data$y - model1(mod, data)
  sqrt(mean(diff^2))
}
```

```{r}
sim1_dist <- function(a1, a2) {
  measure_distance(c(a1, a2), sim1)
}

models <- models %>%
  mutate(dist = purrr::map2_dbl(a1, a2, sim1_dist)) %>%
  arrange(models, dist)
```

```{r}
ggplot(sim1, aes(x, y)) + 
  geom_point(size = 2) + 
  geom_abline(data = filter(models, rank(dist) <= 10), aes(intercept = a1, slope = a2, color = -dist))
```

```{r}
ggplot(models, aes(a1, a2)) + 
  geom_point(data = filter(models, rank(dist) <= 10), size = 4, color = "red") + 
  geom_point(aes(color = -dist))
```

```{r}
#perform grid search
grid <- expand.grid(
  a1 = seq(-5, 20, length = 25),
  a2 = seq(1, 3, length = 25)
) %>%
mutate(dist = purrr::map2_dbl(a1, a2, sim1_dist))

grid %>%
  ggplot(aes(a1, a2)) + 
  geom_point(data = filter(grid, rank(dist) <= 10), size = 4, color = "red") + 
  geom_point(aes(color = -dist))
```

```{r}
ggplot(sim1, aes(x, y)) + 
  geom_point(size = 2) + 
  geom_abline(aes(intercept = a1, slope = a2, color = -dist), data = filter(grid, rank(dist) <= 10))
```

```{r}
best <- optim(c(0, 0), measure_distance, data = sim1)

best
```


